import Nav from '../../components/Nav'
import Head from 'next/head'
import Footer from '../../components/Footer'

export default function AppLayout({ children }: any) {
  return (
    <>
      <Head>
        <title>Phynanx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {/* {auth.user || router.pathname != '/' ? (
        children
      ) : (
        <div className={styles.tryconnect}>
          Try to connect to access content
        </div>
      )} */}
        {children}
        <Footer />
      </main>
    </>
  )
}
