import Nav from '../../components/Nav'
import Head from 'next/head'
import Footer from '../../components/Footer'
import { useRouter } from 'next/router'

export default function AppLayout({ children }: any) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Phynanx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        {children}
        {router.pathname != '/account' ? <Footer /> : ''}
      </main>
    </>
  )
}
